name: my_top

on :
  push:
    branches-ignore:
      - "ga-ignore- *"

env:
  EXECUTABLES: "illegal"

jobs:
  checking_coding_style:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Coding Style checker
        run: |
          check.sh $(pwd) $(pwd)
          input=$(pwd)/coding-style-reports.log
          awk -F':' '{print "::error title="$3" coding style error,file="$1",line="$2"::"$4}' $input
          if [ -s $input ]; then
            exit 1
          fi

  check_program_compilation:
    runs-on: ubuntu-latest
    needs: checking_coding_style
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Is Make Woking
        run: make
        timeout-minutes: 2
      - name: Clean useless files
        run: make clean
        timeout-minutes: 1
