name: my_sudo

on :
  push:
    branches-ignore:
      - "ga-ignore- *"

jobs:
  checking_coding_style:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Coding Style checker
        run: |
          check.sh $(pwd) $(pwd)
          input=$(pwd)/coding-style-reports.log
          awk -F':' '{print "::error title="$3" coding style error,file="$1",line="$2"::"$4}' $input
          if [ -s $input ]; then
            exit 1
          fi
